<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-18T16:12:38Z" name="Default suite" finished-at="2024-09-18T16:12:47Z" duration-ms="9381">
    <groups>
    </groups>
    <test started-at="2024-09-18T16:12:38Z" name="Default test" finished-at="2024-09-18T16:12:47Z" duration-ms="9381">
      <class name="faxesTests.TC_09_ValidateUI">
        <test-method is-config="true" signature="startWebDriver()[pri:0, instance:faxesTests.TC_09_ValidateUI@1d572e62]" started-at="2024-09-18T10:12:38Z" name="startWebDriver" finished-at="2024-09-18T10:12:41Z" duration-ms="2995" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startWebDriver -->
        <test-method signature="TC_09()[pri:0, instance:faxesTests.TC_09_ValidateUI@1d572e62]" started-at="2024-09-18T10:12:41Z" name="TC_09" finished-at="2024-09-18T10:12:46Z" duration-ms="5624" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at faxesTests.TC_09_ValidateUI.TC_09(TC_09_ValidateUI.java:39)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_09 -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:faxesTests.TC_09_ValidateUI@1d572e62]" started-at="2024-09-18T10:12:46Z" name="closeDriver" finished-at="2024-09-18T10:12:47Z" duration-ms="722" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- faxesTests.TC_09_ValidateUI -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
